### ISSUE TITLE
Garage Door "Has stop step" option bug

### ISSUE THREAD

**Issue by pilot1981** [RavenSystem/esp-homekit-devices#423]
Hi,
All worked fine with my two garage door and ravencore 0.8.7.

Today I tried to update to 0.9.2 version with has stop step on, but I notice when I send open command, sonoff start relay and start again relay after about 1 second, so garage door stop and don’t open....

Config of has stop step is always on...and before upgrade all work fine....

My configuration error or a bug?

**Comment by RavenSystem** [comment]
Bug, sure. Disable "has stop step" until I release a fix. Sorry.

**Comment by RavenSystem** [comment]
Fixed in 0.9.3.

**Comment by pilot1981** [comment]
I updated to 0.9.3: with has stop step off, garage door stop if I press again button: it’s ok for you?

**Comment by RavenSystem** [comment]
@pilot1981 Ok, now enable "has stop step" and see if your garage door change way of motion when it is moving and you press HomeKit button. It must stop and then move again.

**Comment by skanico** [comment]
Hello, I updated to 0.9.6 and the "has stop" function still doesn't work as expected (not really an issue for me though, as I don't use HomeKit button to invert the motion) - physical buttons still do the work -.
Everything else works fine for me.

**Comment by pilot1981** [comment]
Hi,
Sorry for delay in my answer.

I tried with and whiteout has stop step feature but behavior don’t change: with both configuration, when garage is opening or closing and I use again button from app, garage door stop and when I click again garage door start again to opening/closing...

What is it wrong?

**Comment by pilot1981** [comment]
@ravensystsem Sorry, but also in 1.0.0 RC version has stop step feature don’t change behavior of device: it seem to do nothing...

**Comment by pilot1981** [comment]
@RavenSystem Sorry, but also in 1.0.0 RC version has stop step feature don’t change behavior of device: it seem to do nothing...

**Comment by RavenSystem** [comment]
In my case it works perfectly, when door is opening and when door is closing, with and without open sensor.

**Comment by pilot1981** [comment]
yes, also for me works fine, but if I setup "has stop step" to NO, it works in same way...very strange...

**Comment by RavenSystem** [comment]
Can you explain with detail your issue??

**Comment by pilot1981** [comment]
with setup "has stop step" to NO, I open garage door successful, during garage door opening I click again on same button to stop garage door, and garage door stop  successful...

If I understood good: with setup "has stop step" to NO, garage door couldn't stop during opening/closing operation...

**Comment by pilot1981** [comment]
Hi @RavenSystem,
I would confirm bug.

With has stop step enabled, if garage door is opening and I send command garage door stop correctly but after few second my sonoff send again signal to garage door so garage door start again to move...

I don’t think this is correct behavior...I would use this feature to stop garage door in any position I prefer...

**Comment by pilot1981** [comment]
I have only close sensor.

Question: this feature require also open sensor?

**Comment by pilot1981** [comment]
Please @RavenSystem can you open again it and correct this bug?

**Comment by RavenSystem** [comment]
"has stop step" works perfectly. This option is not for stop your door. That option is not implemented in Apple HomeKit; it is to avoid to stop it pushing action button twice instead one.
